version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-casaapp
    environment:
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
    volumes:
      - .\datos:/var/lib/mysql
      - .\init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "3080:80"
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
volumes:
  datos-mariadb: